### ISSUE TITLE
Replace SOUND.txt files with SOUND.wav files?

### ISSUE THREAD

**Issue by ThatcherC** [pine64/OpenPineBuds#14]
Would it make sense to have the sound files stored as .wav files in this repo? I think it'd be convenient to be able to listen to them without having to use the convert tool.  I also think it'd be nicer to have the actual audio files in the source tree than long text files of hex values. The Makefile(s) could be modified to run the `convert.sh` script and create the sound.txt files as part of the build process. This change would also greatly simplify the process of swapping in new sound files on personal copies.

I'm looking at how to do this with the Makefiles but wanted to see if it seems like a good idea before I get too far - let me know what you think!

**Comment by Ralim** [comment]
I would support this, it would be far more logical for most users.

**Comment by WebWire-NL** [comment]
It would be logical but i think if you would push all the uncompressed wav files the whole repository would be a lot bigger, better use the build process to convert them to wav's

**Comment by ThatcherC** [comment]
Cool! I will take a deeper look. I'll keep an eye on the file sizes too - it'd definitely be nice to keep the repo size small. I'd suspect that a WAV file using byte encoding would be smaller than the text files already, so hopefully that's no problem.

**Comment by lizz-34** [comment]
Can we close this? https://github.com/pine64/OpenPineBuds/pull/28
