### ISSUE TITLE
Questions about PineBuds Pro

### ISSUE THREAD

**Issue by elamn1** [pine64/OpenPineBuds#19]
These are not related to this firmware, but I think I can get the best answer here.

What is [this "Windows base programmer utility"](https://files.pine64.org/os/PineBudsPro/PineBuds%20Pro%20programmer%20v1.48.zip) on wiki?
Is it the utility developed by Bestechnic for their BES 2300YP SoC?

What is [this "factory default firmware build"](https://files.pine64.org/os/PineBudsPro/AC08_20221102.bin) on wiki?
Is it the firmware that Pine Store currently pre-installs to PineBuds Pro?
Who developed it (e.g. Pine Store, Bestechnic)? What is its license?

What is [this "factory default OTA build"](https://files.pine64.org/os/PineBudsPro/ota_boot_rel_8054309a08.bin) on wiki?
What is the difference from "factory default firmware build"?
Who developed it and what is its license?

What is [this "PineBuds Pro "Little Whale" SDK date:20221128"](https://files.pine64.org//SDK/PineBudsPro/PineBudsPro_SDK-20221128.7z) on the wiki?
Who developed it? What is its license?
Is [the software in this repository](https://github.com/pine64/OpenPineBuds) based on it?

**Comment by Ralim** [comment]
> These are not related to this firmware, but I think I can get the best answer here.

These are best answered in the chat; as they have nothing to do with repo
> 
> What is [this "Windows base programmer utility"](https://files.pine64.org/os/PineBudsPro/PineBuds%20Pro%20programmer%20v1.48.zip) on wiki?
> Is it the utility developed by Bestechnic for their BES 2300YP SoC?

Correct this is the tool from Bestechnic.

> 
> What is [this "factory default firmware build"](https://files.pine64.org/os/PineBudsPro/AC08_20221102.bin) on wiki?
> Is it the firmware that Pine Store currently pre-installs to PineBuds Pro?

Yes

> Who developed it (e.g. Pine Store, Bestechnic)? What is its license?

Developed by _someone_; most likely a design house. For Pine64 Store. No License is known, it is completely closed source and we cant get the source.

> 
> What is [this "factory default OTA build"](https://files.pine64.org/os/PineBudsPro/ota_boot_rel_8054309a08.bin) on wiki?
> What is the difference from "factory default firmware build"?

Its the part that goes in the OTA partition.

> Who developed it and what is its license?

Same as above

> 
> What is [this "PineBuds Pro "Little Whale" SDK date:20221128"](https://files.pine64.org//SDK/PineBudsPro/PineBudsPro_SDK-20221128.7z) on the wiki?
> Who developed it? What is its license?

No idea whom; a different design house than the one that did the closed source code; again organised and paid for by Pine64 Store. License is unknown other than that we have the source. Same as most source code from China.

> Is [the software in this repository](https://github.com/pine64/OpenPineBuds) based on it?

Yes

**Comment by WebWire-NL** [comment]
Maybe add a link to https://github.com/pine64/OpenPineBuds/discussions on the homepage of this project like someone mentioned earlier. Because there seems to be no central place to discuss all stuff.
