### ISSUE TITLE
"2.5W Qi Wire Power Receiver Datasheet (Unpopulated)"?

### ISSUE THREAD

**Issue by elamn1** [pine64/OpenPineBuds#21]
What "2.5W Qi Wire Power Receiver Datasheet (Unpopulated)" means? I don't understand what "unpopulated" means in this context?

https://wiki.pine64.org/index.php?title=PineBuds_Pro&diff=prev&oldid=15216

**Comment by Ralim** [comment]
Hia, this is a question more suited to the community chats than github fwiw. 

I would suggest doing a little research first 😁

But unpopulated in this case means it's not populated on the PCB (aka fitted), so the circuit board has the connections for the chip and it's supporting parts but they are not fitted. This is done for features like this that are not essential but that someone may want to solder in themselves.

**Comment by elamn1** [comment]
> Hia, this is a question more suited to the community chats than github fwiw.

Sorry : ( I don't know where is discussion about PineBuds Pro (hardware). Maybe I should check IRC.

> But unpopulated in this case means it's not populated on the PCB (aka fitted), so the circuit board has the connections for the chip and it's supporting parts but they are not fitted. This is done for features like this that are not essential but that someone may want to solder in themselves.

Chip? Isn't that need just the wiring from the Qi component to the charging points?
So PineBuds Pro case PCB has ready places for the Qi component, to which I can solder it? Have you considered adding support for Qi to this firmware? I mean, control is needed when the device has both Qi and USB, that power feed from both at the same time would not break the device, right?
